---
ID: "a9f0c713-81bb-470c-b741-52b0d3bd5cd0"
Parent: "44e4bf0e-317c-49a1-919f-37accabe32d7"
Template: "44e4bf0e-317c-49a1-919f-37accabe32d7"
Path: /sitecore/templates/Basiscore/Content Authoring Guide/Carousel Slide/__Standard Values
SharedFields:
- ID: "9135200a-5626-4dd8-ab9d-d665b8c11748"
  Hint: __Never publish
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180621T133232Z
    - ID: "42228296-49c6-4bcc-b9cc-844fdd202329"
      Hint: Is Active
      Value: 1
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0980caf8-c336-4d04-ac2c-0ccbafdefc78"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20180625T131618Z
